/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_des_DesTest */

#ifndef _Included_com_test_des_DesTest
#define _Included_com_test_des_DesTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_des_DesTest
 * Method:    DevOrResStr
 * Signature: (Lcom/test/des/DesUtil;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_des_DesTest_DevOrResStr__Lcom_test_des_DesUtil_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_test_des_DesTest
 * Method:    DevOrResStr
 * Signature: (Lcom/test/des/DesUtil;Ljava/lang/String;Ljava/lang/String;Ljava/security/Key;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_des_DesTest_DevOrResStr__Lcom_test_des_DesUtil_2Ljava_lang_String_2Ljava_lang_String_2Ljava_security_Key_2Z
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
